<a href="https://colab.research.google.com/github/pabloboada88/Compute-science/blob/main/L1_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 1. Matrices

### 1. Introducción


A lo largo de las prácticas utilizaremos principalmente el paquete de Python `numpy` y también el subpaquete `linalg` de `scipy`, luego es **muy importante** importarlos siempre antes de empezar la sesión. 

In [1]:
import numpy as np
import scipy.linalg as la

Por comodidad, los hemos llamado con un nombre abreviado. Si se nos olvida importarlos, al ejecutar algún comando que los necesite nos saldrá un mensaje de error del tipo siguiente: `NameError: name 'np' is not defined`.

**Los escalares** se introducen directamente y, en el caso de números decimales, separando la parte entera de la decimal con un
punto. 

In [2]:
a=2
b=3.5
print('[a,b] =',[a,b])

[a,b] = [2, 3.5]


Podemos **redondear** un número concreto $x$ a $d$ decimales mediante `round(x, d)`.

In [3]:
round(3.1415926, 2)

3.14

### 2. Matrices

Con el comando `np.array([ vector ])` podemos crear listas como la anterior, pero además podremos operar con ellas. Observemos que el _output_ obtenido es un poco diferente si usamos `print`.

In [4]:
v=np.array([[2,3]])
3*v

array([[6, 9]])

In [5]:
print(3*v)

[[6 9]]


También es posible redondear en global todas las entradas de un vector con `np.round(v, d)`.

In [6]:
np.round(np.array([[1/9, 11/9]]), 2)

array([[0.11, 1.22]])

Los vectores los podemos introducir en modo fila o columna, y con varios vectores podemos crear también **matrices** de las dimensiones que deseemos.

In [10]:
v1=np.array([[1,2,3]])      # vector de dimensión (1,3)
v2=np.array([[5],[7],[-1]])         # vector de dimensión (3,1)
M=np.array([[1, 0, -3],
            [2, 5, 0],
            [1, 1, -4]])    # matriz de dimensión (3,3)

In [11]:
v1

array([[1, 2, 3]])

In [12]:
print(M)
print(v2)

[[ 1  0 -3]
 [ 2  5  0]
 [ 1  1 -4]]
[[ 5]
 [ 7]
 [-1]]


Podemos comprobar las **dimensiones** de los vectores y la matriz anteriores añadiéndole `.shape` a sus nombres. Asimismo, con `.size` obtendremos el número total de elementos que poseen.

In [13]:
v1.shape

(1, 3)

In [14]:
M.shape

(3, 3)

In [15]:
v2.size

3

In [16]:
M.size

9

Otra forma que puede ser útil para crear matrices es uniendo vectores previos, a través de `np.vstack`. Si los vectores están en columna, usaremos `np.hstack` para _unirlos horizontalmente_.

In [17]:
v3=np.array([[0,1,0]])
v4=np.array([[1,0,0]])
N=np.vstack([v3,v4,v1])   # matriz creada uniendo por filas v3, v4 y v1
print(N)

[[0 1 0]
 [1 0 0]
 [1 2 3]]


In [74]:
v5=np.array([[1],
            [0],
            [0]])
v6=np.array([[1],
            [1],
            [1]])
L=np.hstack([v2,v5,v6])   # en este caso, matriz creada uniendo por columnas v2, v5 y v6
print(L)

[[ 5  1  1]
 [ 7  0  1]
 [-1  0  1]]


### 3. Algunas matrices especiales

Existen comandos que nos permiten crear directamente algunos tipos de matrices que utilizaremos frecuentemente. Por ejemplo, con `np.zeros((m,n))` podremos crear una **matriz nula** de dimensión $m \times n$. La **matriz identidad** de dimensión $n$ la podemos construir a través de `np.eye(n)`, mientras que `np.ones((m,n))` nos crea una **matriz de unos** de dimensión $m\times n$.

In [22]:
print(np.zeros((2,3)))
print(np.ones((4,5)))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Una **matriz de entradas constantes** $k$ puede ser construida de dos formas diferentes. Por ejemplo, a través del comando `np.full((m, n), k)`, o también _multiplicando_ el escalar $k$ por una matriz de unos (esto conlleva una _operación con matrices_ que veremos en la siguiente sección).

In [25]:
print(np.full((3,4), 7))
print(7*np.ones((5,5))-np.eye(5))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[6. 7. 7. 7. 7.]
 [7. 6. 7. 7. 7.]
 [7. 7. 6. 7. 7.]
 [7. 7. 7. 6. 7.]
 [7. 7. 7. 7. 6.]]


Una **matrix diagonal** con entradas $a_1, \ldots, a_n$ puede ser creada a partir de `np.diag([ ])`, introduciendo dentro de los corchetes las entradas. Asimismo, con `np.diag(A)` podemos obtener un vector cuyas entradas son los elementos de la diagonal de la matriz $A$.

In [24]:
A=np.diag([1,2,3,4,5])
print(A)

print(np.diag(L))

D=np.diag(np.diag(L))     # De esta forma obtenemos una matriz diagonal a partir de la diagonal de L
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[5 0 1]
[[5 0 0]
 [0 0 0]
 [0 0 1]]


### 4. Operaciones con matrices

Las **operaciones aritméticas** usuales `+,-,*,/` (suma, resta, multiplicación y división) y `**` (potencia) sobre listas se aplican **elemento a elemento**.

In [26]:
print(M)
print(N)
print(M+N)

[[ 1  0 -3]
 [ 2  5  0]
 [ 1  1 -4]]
[[0 1 0]
 [1 0 0]
 [1 2 3]]
[[ 1  1 -3]
 [ 3  5  0]
 [ 2  3 -1]]


In [75]:
print(L-M)
print(L)
print(L-1)

[[ 4  1  4]
 [ 5 -5  1]
 [-2 -1  5]]
[[ 5  1  1]
 [ 7  0  1]
 [-1  0  1]]
[[ 4  0  0]
 [ 6 -1  0]
 [-2 -1  0]]


In [30]:
print(M)
print(N)

[[ 1  0 -3]
 [ 2  5  0]
 [ 1  1 -4]]
[[0 1 0]
 [1 0 0]
 [1 2 3]]


In [29]:
print(M*N)                # multiplicada cada entrada de M por su correspondiente entrada en N. 
                          # NO es el producto de matrices estándar
print(M*v1)
print(M*v2)

[[  0   0   0]
 [  2   0   0]
 [  1   2 -12]]
[[  1   0  -9]
 [  2  10   0]
 [  1   2 -12]]
[[  5   0 -15]
 [ 14  35   0]
 [ -1  -1   4]]


In [31]:
print(M**2)        # eleva cada elemento de M al cuadrado
print(2*v)    
print(2**(2*v))    # eleva el escalar 2 a cada entrada del vector 2*v=[4,7], es decir, crea el vector [2^4, 2^7]

[[ 1  0  9]
 [ 4 25  0]
 [ 1  1 16]]
[[4 6]]
[[16 64]]


Para realizar el **producto de matrices estándar** entre dos matrices compatibles $M$ y $N$, debemos usar `M @ N` (los espacios realmente no son necesarios) o bien `M.dot(N)`.

In [76]:
print(L)
print(v2)
print(L @ v2)
print(L.dot(v2))

[[ 5  1  1]
 [ 7  0  1]
 [-1  0  1]]
[[ 5]
 [ 7]
 [-1]]
[[31]
 [34]
 [-6]]
[[31]
 [34]
 [-6]]


In [68]:
M.dot(v1)     # Evidentemente, si las dimensiones no son compatibles, nos devolverá un mensaje de error

ValueError: ignored

No hay un símbolo específico para calcular **potencias de una matriz** (recordemos que `**` calcula las potencias de los elementos, no de la matriz en sí). Por tanto, usaremos el comando `np.linalg.matrix_power(M, k)` proveniente del subpaquete `linalg` de `numpy` (recordemos que lo tenemos abreviado por `np`) para calcular la $k$-ésima potencia de $M$, i.e. $M^k$. 

In [34]:
print(np.linalg.matrix_power(L,3))         # L^3 calculada a través de la función np.linalg.matrix_power
print(L@L@L)                               # L^3 calculada a través de multiplicar L tres veces

[[183  31  43]
 [211  34  49]
 [-37  -6  -7]]
[[183  31  43]
 [211  34  49]
 [-37  -6  -7]]


También es posible, por comodidad, abreviar el nombre de este comando, por ejemplo por `mpow`. 

In [35]:
from numpy.linalg import matrix_power as mpow 

# Típico error: "from np.linalg import matrix_power as mpow", no podemos usar la abreviatura np.linalg !!

print(mpow(L, 3))

[[183  31  43]
 [211  34  49]
 [-37  -6  -7]]


La **traspuesta de una matriz** se puede calcular a partir del comando `.T`.

In [58]:
print(v1.T)
print(v1@v1.T)     # producto escalar de v1 con v1

[[1]
 [2]
 [3]]
[[14]]


Usando el anterior comando, podemos calcular _manualmente_ la norma de un vector $v$, aunque también existe el comando `la.norm(v)` para calcularlo directamente.

In [64]:
print(np.sqrt(v1@v1.T))  # manualmente: de esta manera, el resultado obtenido es una matriz (pues multiplicamos dos matrices)
print(np.sqrt(np.sum(v1*v1)))  # manualmente: de esta manera, multiplicamos elemento a elemento v1, sumamos y raíz cuadrada
print(la.norm(v1))

[[3.74165739]]
3.7416573867739413
3.7416573867739413


La **matriz inversa** de una matriz $M$ puede calcularse a través de `la.inv(M)`; su **traza** mediante `np.trace(M)`, su **determinante** a través de `la.det(M)` y su **rango** mediante `np.linalg.matrix_rank(M)`.

In [77]:
print(L)
print(np.trace(L))
print(la.det(L))    # distinto de cero, luego podemos calcular sin problema su inversa
print(la.inv(L))
print(L.dot(la.inv(L)))

[[ 5  1  1]
 [ 7  0  1]
 [-1  0  1]]
6
-8.0
[[-0.     0.125 -0.125]
 [ 1.    -0.75  -0.25 ]
 [ 0.     0.125  0.875]]
[[ 1.00000000e+00  1.11022302e-16 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [66]:
from numpy.linalg import matrix_rank as rank     # abreviamos el comando para calcular rangos

rank(L)

1

### 5. Submatrices


Es posible trabajar con **submatrices** extraídas de una matriz $M$, usando expresiones como las siguientes:

1. `M[i-1,j-1]` para el elemento que ocupa la posición fila $i$ y columna $j$
2. `M[i-1:i,:]` para la fila $i$
3. `M[:,j-1:j]` para la columna $j$
4. `M[r-1:s,:]` para la submatriz formada por las filas entre la $r$ y la $s$
5. `M[[r-1,s-1],:]` para la submatriz formada por las filas $r$ y $s$

Observemos que estas expresiones también nos permiten hacer modificaciones en una matriz que ya ha sido introducida. Así, por ejemplo, si queremos modificar la fila $i$ de $M$, podemos escribir `M[i-1,:] = nueva fila`.

Es importante recordar que los índices comienzan en el número 0 (i.e. la posición primera es el índice 0), por ello para seleccionar la fila $i$ escribimos el índice `i-1`. Además, por comodidad podemos utilizar el índice `-1` para seleccionar el último elemento, `-2` para el penúltimo, etc. Asimismo, los rangos `a:b` por defecto no seleccionan el último elemento `b`, luego acabaría en el `b-1` (por tanto, el rango `i-1:i` realmente solo contiene un número, el $i-1$).

Ante la posible duda de porqué no usamos `M[:,j-1]` para seleccionar la columna $j$ de $M$ en vez de `M[:,j-1:j]`, es importante mencionar que la primera opción devuelve una lista y no un vector columna, luego no podríamos operar matricialmente de forma correcta. La segunda opción sí que devuelve un vector columna y esto se debe a una cuestión un poco técnica: aunque `j-1:j` solamente contiene el número $j-1$, tiene estructura de rango, luego _está en concordancia_ con el formato de filas seleccionado.

In [83]:
print(L)

[[ 5  1  1]
 [ 7  8  1]
 [-1  0  1]]


In [84]:
print(L[1,0])       # seleccionamos el elemento (2,1) de la matriz L
L[1,1]=8            # cambiamos el elemento (2,2) de la matriz L por un 8, es decir, cambiamos el 0 por 8
print(L)

7
[[ 5  1  1]
 [ 7  8  1]
 [-1  0  1]]


Observemos que $L$ ha cambiado. Si no queríamos perder la matriz $L$ inicial, sería mejor hacer las modificaciones sobre una _copia_ de la matriz $L$, digamos $L1$. Esto es posible mediante el comando `L.copy()`. (¡No vale con asignar `L1=L`, pues los cambios se realizarán igualmente sobre ambas matrices!)

In [85]:
L1=L.copy()
L1[:,1]=[5,5,4]
print(L1)
print(L)

[[ 5  5  1]
 [ 7  5  1]
 [-1  4  1]]
[[ 5  1  1]
 [ 7  8  1]
 [-1  0  1]]


In [80]:
print(L[[1,2],:])    # seleccionamos las dos últimas filas de L
print(L[1:,:])       # equivalentemente: "1:" significa que seleccionamos el rango que empieza en el 1 hasta "el final"

[[ 7  8  1]
 [-1  0  1]]
[[ 7  8  1]
 [-1  0  1]]


In [87]:
I=np.random.rand(5,5)         # creamos una matriz 5 x 5 de elementos aleatorios
print(I)
print(I[[1,-2],0:4])          # seleccionamos las filas 2 y 4, y las columnas de la 1 a la 4

[[0.37711251 0.10357807 0.51057289 0.630776   0.78167871]
 [0.48227887 0.66050856 0.66828233 0.31573373 0.66772668]
 [0.66768389 0.01811994 0.10110726 0.16221111 0.85324423]
 [0.82749818 0.76201721 0.76262515 0.37483555 0.60986964]
 [0.00509758 0.41355027 0.88652064 0.7522179  0.71186088]]
[[0.48227887 0.66050856 0.66828233 0.31573373]
 [0.82749818 0.76201721 0.76262515 0.37483555]]


In [82]:
print(I[4:5,:])                 # seleccionamos la última fila de I
print(I[:,2:3])                 # seleccionamos la tercera columna de I

[[0.8099012  0.44896305 0.64001009 0.57682962 0.37654376]]
[[0.38637004]
 [0.96347209]
 [0.05502902]
 [0.76623949]
 [0.64001009]]


### 6. Ejercicios

1. Dados los números $x = 14.32$, $y = 27.12$ y $z = 3.5$, calcula el valor de la expresión $\dfrac{8x+y^2}{2-\sqrt[6]{x^3+\frac{1}{z}}}$. (Solución: -476.424)


2. Crea la matriz $M=(m_{ij})$ de orden $50 \times 50$ tal que $m_{ii} = 10$ y $m_{ij} = 0$ para $i\neq j$.


3. Dados los vectores $u = \left(\frac{1}{4}, -\frac{1}{6}, \frac{5}{6}\right)$ y $v = \left(\frac{1}{5}, \frac{3}{4}, -\frac{2}{3}\right)$, calcula el producto escalar de ambos vectores. (Solución: -0.63055)


4. Dada la matriz $A=\begin{pmatrix} 1&2&3\\7&8&9\\4&5&6\end{pmatrix}$, calcula la matriz $Z=A^3+16A^2-A^{\text{t}}+2I$, siendo $A^{\text{t}}$ la transpuesta de $A$ e $I$ la matriz identidad $3\times 3$. (Solución: $Z=\begin{pmatrix} 847&1034&1232\\3130&3879&4633\\1986&2454&2933 \end{pmatrix}$)


5. Considera el vector $V=\begin{pmatrix} 1\\7\\6 \end{pmatrix}$. Calcula la matriz $ZV$, siendo $Z$ la matriz del ejercicio anterior. (Solución: $ZV=\begin{pmatrix} 15477\\ 58081\\ 36762\end{pmatrix}$)


6. Calcula el determinante de la siguiente matriz (estas matrices se denominan _circulantes_ ). $C=\begin{pmatrix} 1& 2& 3& 4& 5\\2& 3& 4& 5& 1 \\ 3& 4& 5& 1& 2\\ 4& 5& 1& 2& 3\\ 5& 1& 2& 3& 4\end{pmatrix}$. (Ayuda: puedes introducir rápidamente la matriz C con el comando `C = la.circulant([1,2,3,4,5])[:,[0,4,3,2,1]]`) (Solución: 1875)

In [69]:
x=14.32 
y=27.12
z=3.5
W=8*x+y**2
D=2-(x**3+1/x)**(1/6)
print(W/D)


-476.4364607272688


In [43]:
print(10*np.eye(50))

[[10.  0.  0. ...  0.  0.  0.]
 [ 0. 10.  0. ...  0.  0.  0.]
 [ 0.  0. 10. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ...  0. 10.  0.]
 [ 0.  0.  0. ...  0.  0. 10.]]


In [51]:
u=np.array([[1/4,-1/6,5/6]])
v=np.array([[1/5,3/4,-2/3]])
print(u*v)
np.sum(u*v)

[[ 0.05       -0.125      -0.55555556]]


-0.6305555555555555

In [62]:
A=np.array([[1,2,3],[7,8,9],[4,5,6]])
Z=(A @ A @ A)+(16*A @ A)-(A.T)+(2*np.eye(3))
print(Z)


[[ 847. 1034. 1232.]
 [3130. 3879. 4633.]
 [1986. 2454. 2933.]]


In [94]:
V=np.array([[1],[7],[6]])
Z=([[847,1034,1232],[3180,3879,4633],[1986,2454,2933]])
ZA=Z @ V
print(ZA)

[[15477]
 [58131]
 [36762]]


In [95]:
C = la.circulant([1,2,3,4,5])[:,[0,4,3,2,1]])

SyntaxError: ignored